version: '3.7'

services:

  mysql:
    platform: linux/x86_64
    image: mysql
    command: --max_allowed_packet=32505856
    container_name: mysql-nestjs
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nodejs
    ports:
      - "3308:3306"
    volumes:
      # Mysql
      - db:/var/lib/mysql
    networks:
      - nodejss

  web:
    depends_on:
      - mysql
    build: ./
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
    restart: unless-stopped
    container_name: web-nestjs
    stdin_open: true
    tty: true
    networks:
      - nodejss

volumes:
  db:

networks:
  nodejss: